Repository arkatsy/zals-ecommerce, pull requests merged in 2023-02, with the labels that each got.

#14 9 create primitives for the header bar
  package.json
  pnpm-lock.yaml
  public/favicon.svg
  src/components/ui/Logo.tsx
  src/components/ui/buttons/menu/AuthButton.tsx
  src/components/ui/buttons/menu/BookmarkButton.tsx
  src/components/ui/buttons/menu/CartButton.tsx
  src/components/ui/buttons/menu/LogoButton.tsx
  src/components/ui/buttons/menu/MenuButton.tsx
  src/components/ui/buttons/menu/PrimaryCategory.tsx
  src/components/ui/buttons/menu/index.ts
  src/components/ui/icons/IconAuth.tsx
  src/components/ui/icons/IconBookmark.tsx
  src/components/ui/icons/IconCart.tsx
  src/components/ui/icons/IconMenu.tsx
  src/components/ui/icons/index.ts
  src/components/ui/icons/shared.ts
  src/pages/_document.tsx
  src/pages/bookmarks/index.tsx
  src/pages/cart/index.tsx
  src/pages/category/kids.tsx
  src/pages/category/man.tsx
  src/pages/category/women.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
Labels: UI, frontend

#16 15 add a sizing way to the primarycategory component
  src/components/ui/buttons/menu/PrimaryCategory.tsx
Labels: UI, frontend, fix

#17 10 create the header bar
  src/components/ui/Header.tsx
  src/components/ui/Layout.tsx
  src/components/ui/buttons/menu/AboutUsButton.tsx
  src/components/ui/buttons/menu/AuthButton.tsx
  src/components/ui/buttons/menu/BookmarkButton.tsx
  src/components/ui/buttons/menu/CartButton.tsx
  src/components/ui/buttons/menu/LogoButton.tsx
  src/components/ui/buttons/menu/MenuButton.tsx
  src/components/ui/buttons/menu/PrimaryCategory.tsx
  src/pages/about-us/index.tsx
  src/pages/bookmarks/index.tsx
  src/pages/cart/index.tsx
  src/pages/category/kids.tsx
  src/pages/category/man.tsx
  src/pages/category/women.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: UI, frontend

#20 Added accessibility for the header navigation
  src/components/ui/buttons/menu/AuthButton.tsx
  src/components/ui/buttons/menu/BookmarkButton.tsx
  src/components/ui/buttons/menu/CartButton.tsx
  src/components/ui/buttons/menu/LogoButton.tsx
  src/components/ui/buttons/menu/MenuButton.tsx
Labels: UI, frontend, enhancement

#23 22 clean up the code and refactor if needed
  package.json
  pnpm-lock.yaml
  src/components/ui/AboutUsLink.tsx
  src/components/ui/Header.tsx
  src/components/ui/IconWrappers.tsx
  src/components/ui/Icons.tsx
  src/components/ui/Layout.tsx
  src/components/ui/Logo.tsx
  src/components/ui/MenuOverlay.tsx
  src/components/ui/PrimaryCategory.tsx
  src/components/ui/buttons/menu/AuthButton.tsx
  src/components/ui/buttons/menu/BookmarkButton.tsx
  src/components/ui/buttons/menu/CartButton.tsx
  src/components/ui/buttons/menu/MenuButton.tsx
  src/components/ui/buttons/menu/index.ts
  src/pages/category/kids.tsx
  src/pages/category/man.tsx
  src/pages/category/women.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: UI, frontend, fix, clean up, refactor

#27 25 create products grid
  next.config.js
  public/kids.jpg
  public/man.jpg
  public/women.jpg
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/ProductCard.tsx
  src/components/ProductsGrid.tsx
  src/components/Sidebar.tsx
  src/lib/utils.ts
  src/pages/category/kids.tsx
  src/pages/category/man.tsx
  src/pages/category/women.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: UI, frontend
